### PR TITLE
Fix Observability CI workflow checks

### PR DESCRIPTION
**Pull request by ps48**
### Description
* Add job scheduler to dashboards-observability CI, SQL plugin recently added this as an dependency leading the observability CI failing waiting for Job scheduler plugin. Related upstream PR: https://github.com/opensearch-project/sql/pull/2834

* Removed datasources tests from observability plugin 
* Update link checker to exclude localhost links 
* Fixed link for getting strated

### Issues Resolved
https://github.com/opensearch-project/dashboards-observability/issues/1886

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by RyanL1997 — APPROVED** [review]

**Comment by RyanL1997** [comment]
Should we also backport this?

**Comment by derek-ho** [comment]
Seems like CI still failing on install: https://github.com/opensearch-project/dashboards-observability/actions/runs/10292034044/job/28485578654?pr=2046

**Comment by ps48** [comment]
@derek-ho The workflows are still using the old workflow file. I think the workflows will only get updated once merged in.

**Comment by derek-ho** [comment]
@ps48 it looks like its a different workflow file, I think you need to make the same change in this file: https://github.com/opensearch-project/dashboards-observability/blob/main/.github/workflows/integration-tests-workflow.yml#L56 here

**Comment by ps48** [comment]
Thanks! @derek-ho that was a good catch, updated the PR

**Review by joshuali925 — APPROVED** [review]

**Review by sumukhswamy — APPROVED** [review]

**Review by YANG-DB — APPROVED** [review]

**Review by derek-ho — APPROVED** [review]

**Pull request merged**
