### PR TITLE
[Dashboard listing] update edit url and view url

### PR DESCRIPTION
**Pull request by kavilla**
### Description
Update to include BASE_URL if basePath is defined. Since create url is just a direct nav and needs the basePath when passing props to the provider, the source code no longer appends the basePath to keep these URLs consistent.

A feature should consolidate the basePaths in the dashboard listing service so that createUrl also adds the base path. At which point we no longer need the base path.

Also removed some rogue console logs and setToast.

Core PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3922

### Issues Resolved
n/a

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by ps48 — APPROVED** [review]
Thanks for the PR 👍🏽

**Review by derek-ho — APPROVED** [review]

**Review by dblock — CHANGES_REQUESTED** [review]
This needs tests.

**Comment by kavilla** [comment]
Core repo PR has been merged and backported to 2.7. This PR can be merged.

**Comment by kavilla** [comment]
@joshuali925 seems like 2.x backport is failing but I'm not sure 2.x in synced with main and 2.7 as it seems a couple commits are missing. Is this expected?

**Comment by joshuali925** [comment]
@kavilla Yes, 2.x/2.7 diverged from main and led to many conflicts. The backports to 2.7 were done manually in #382 and #385. I didn't have the time to do the same for 2.x.

At this moment we would expect 2.x and 2.7 to be exactly the same, i'm planning to sync them later after 2.7 released to save some effort. Let me know if 2.x is meaningful now and I'll sync them sooner

**Pull request merged**
