### PR TITLE
Update traces integration tests

### PR DESCRIPTION
**Pull request by rupal-bq**
### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by rupal-bq** [comment]
```
maharup@b0f1d879dff7 dashboards-observability % yarn cypress run --spec ".cypress/integration/4_trace_analytics_dashboard.spec.js" 
yarn run v1.22.19
$ /Users/maharup/GitRepoWorkspace/OpenSearch-Dashboards/plugins/dashboards-observability/node_modules/.bin/cypress run --spec .cypress/integration/4_trace_analytics_dashboard.spec.js
The `experimentalNetworkStubbing` configuration option was removed in Cypress version `6.0.0`.
It is no longer necessary for using `cy.intercept()` (formerly `cy.route2()`).

You can safely remove this option from your config.
Nothing to watch. Set the "cypress-watch-and-reload" object in the Cypress configuration
see https://github.com/bahmutov/cypress-watch-and-reload#use

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    6.9.1                                                                              │
  │ Browser:    Electron 87 (headless)                                                             │
  │ Specs:      1 found (4_trace_analytics_dashboard.spec.js)                                      │
  │ Searched:   .cypress/integration/4_trace_analytics_dashboard.spec.js                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  4_trace_analytics_dashboard.spec.js                                             (1 of 1)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating


  Dump test data
    ✓ Indexes test data (1952ms)

  Testing dashboard table empty state
    ✓ Renders empty state (7229ms)

  Testing dashboard table
    ✓ Renders the dashboard table (10815ms)
    ✓ Has working breadcrumbs (8933ms)
    ✓ Adds the percentile filters (14106ms)
    ✓ Opens latency trend popover (17019ms)
    ✓ Redirects to traces table with filter (11713ms)

  Testing plots
    ✓ Renders service map (7459ms)
    ✓ Renders plots (6029ms)

  Latency by trace group table
    ✓ Verify columns in Latency by trace group table along with pagination functionality (7423ms)
    ✓ Sorts the Latency by trace group table (7604ms)
    ✓ Verify tooltips in Latency by trace group table (9883ms)
    ✓ Verify Search engine on Trace dashboard (16449ms)

  Testing filters on trace analytics page
    ✓ Verify Change all filters (6810ms)
    ✓ Verify Add filter section (7213ms)

  Dump jaeger test data
    ✓ Indexes test data (1169ms)

  Testing switch mode to jaeger
    ✓ Verifies errors mode columns and data (7880ms)
    ✓ Verifies traces links to traces page (10433ms)
    ✓ Switches to throughput mode and verifies columns and data (7590ms)


  19 passing (3m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        19                                                                               │
  │ Passing:      19                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 minutes, 48 seconds                                                            │
  │ Spec Ran:     4_trace_analytics_dashboard.spec.js                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /Users/maharup/GitRepoWorkspace/OpenSearch-Dashboards/plugi    (9 seconds)
                          ns/dashboards-observability/.cypress/videos/4_trace_analyti               
                          cs_dashboard.spec.js.mp4                                                  


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  4_trace_analytics_dashboard.spec.js      02:48       19       19        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        02:48       19       19        -        -        -  

✨  Done in 188.50s.
```

**Comment by rupal-bq** [comment]
```
maharup@b0f1d879dff7 dashboards-observability % yarn cypress run --spec ".cypress/integration/5_trace_analytics_services.spec.js"
yarn run v1.22.19
$ /Users/maharup/GitRepoWorkspace/OpenSearch-Dashboards/plugins/dashboards-observability/node_modules/.bin/cypress run --spec .cypress/integration/5_trace_analytics_services.spec.js
The `experimentalNetworkStubbing` configuration option was removed in Cypress version `6.0.0`.
It is no longer necessary for using `cy.intercept()` (formerly `cy.route2()`).

You can safely remove this option from your config.
Nothing to watch. Set the "cypress-watch-and-reload" object in the Cypress configuration
see https://github.com/bahmutov/cypress-watch-and-reload#use

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    6.9.1                                                                              │
  │ Browser:    Electron 87 (headless)                                                             │
  │ Specs:      1 found (5_trace_analytics_services.spec.js)                                       │
  │ Searched:   .cypress/integration/5_trace_analytics_services.spec.js                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  5_trace_analytics_services.spec.js                                              (1 of 1)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating


  Testing services table empty state
    ✓ Renders empty state (8014ms)

  Testing services table
    ✓ Renders the services table (10240ms)
    ✓ Searches correctly (7910ms)
    ✓ Verify columns in Services table (6548ms)
    ✓ Navigate from Services to Traces (5778ms)

  Testing service view empty state
    ✓ Renders service view empty state (1903ms)

  Testing service view
    ✓ Renders service view (9127ms)
    ✓ Has working breadcrumbs (16285ms)
    ✓ Renders spans data grid, flyout, filters (12030ms)

  Testing Service map
    ✓ Render Service map (6160ms)

  Testing traces Spans table verify table headers functionality
    ✓ Renders the spans table and verify columns headers (6669ms)
    ✓ Toggle columns and verify the columns hidden text verify rows (7021ms)
    ✓ Show all button Spans table (7086ms)
    ✓ Hide all button Spans table (6654ms)
    ✓ Render Spans table and change data table Density (7225ms)
    ✓ Render Spans table and and click on sort (9907ms)

  Testing traces Spans table and verify columns functionality
    ✓ Renders the spans table and click on first span to verify details (11167ms)
    ✓ Render Spans table and verify Column functionality (7928ms)

  Testing switch mode to jaeger
    ✓ Verifies columns and data (7362ms)
    ✓ Verifies traces links to traces page with filter applied (8904ms)


  20 passing (3m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        20                                                                               │
  │ Passing:      20                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 minutes, 44 seconds                                                            │
  │ Spec Ran:     5_trace_analytics_services.spec.js                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /Users/maharup/GitRepoWorkspace/OpenSearch-Dashboards/plugi    (9 seconds)
                          ns/dashboards-observability/.cypress/videos/5_trace_analyti               
                          cs_services.spec.js.mp4                                                   


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  5_trace_analytics_services.spec.js       02:44       20       20        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        02:44       20       20        -        -        -  

✨  Done in 184.73s.
```

**Comment by rupal-bq** [comment]
```
maharup@b0f1d879dff7 dashboards-observability % yarn cypress run --spec ".cypress/integration/6_trace_analytics_traces.spec.js"  
yarn run v1.22.19
$ /Users/maharup/GitRepoWorkspace/OpenSearch-Dashboards/plugins/dashboards-observability/node_modules/.bin/cypress run --spec .cypress/integration/6_trace_analytics_traces.spec.js
The `experimentalNetworkStubbing` configuration option was removed in Cypress version `6.0.0`.
It is no longer necessary for using `cy.intercept()` (formerly `cy.route2()`).

You can safely remove this option from your config.
Nothing to watch. Set the "cypress-watch-and-reload" object in the Cypress configuration
see https://github.com/bahmutov/cypress-watch-and-reload#use

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    6.9.1                                                                              │
  │ Browser:    Electron 87 (headless)                                                             │
  │ Specs:      1 found (6_trace_analytics_traces.spec.js)                                         │
  │ Searched:   .cypress/integration/6_trace_analytics_traces.spec.js                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  6_trace_analytics_traces.spec.js                                                (1 of 1)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating


  Testing traces table empty state
    ✓ Renders empty state (7666ms)

  Testing traces table
    ✓ Renders the traces table (7871ms)
    ✓ Sorts the traces table (5791ms)
    ✓ Searches correctly (7246ms)

  Testing trace view
    ✓ Renders the trace view (10289ms)
    ✓ Has working breadcrumbs (17528ms)
    ✓ Renders data grid, flyout and filters (14311ms)

  Testing traces table
    ✓ Renders the traces table and verify Table Column, Pagination and Rows Data  (9768ms)

  Testing switch mode to jaeger
    ✓ Verifies columns and data (6638ms)
    ✓ Verifies Trace View (5995ms)


  10 passing (2m)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        10                                                                               │
  │ Passing:      10                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     1 minute, 33 seconds                                                             │
  │ Spec Ran:     6_trace_analytics_traces.spec.js                                                 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /Users/maharup/GitRepoWorkspace/OpenSearch-Dashboards/plugi    (5 seconds)
                          ns/dashboards-observability/.cypress/videos/6_trace_analyti               
                          cs_traces.spec.js.mp4                                                     


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  6_trace_analytics_traces.spec.js         01:33       10       10        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        01:33       10       10        -        -        -  

✨  Done in 109.70s.
```

**Review by ps48 — APPROVED** [review]

**Review by derek-ho — APPROVED** [review]
ty

**Pull request merged**
