### PR TITLE
BugFix: Visuals from Applications available in Dashboards

### PR DESCRIPTION
**Pull request by TackAdam**
### Description
[Describe what this change achieves]
Allowed saved visuals from applications to be viewable from the logs home screen and for them to be added to dashboards.

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by derek-ho — APPROVED** [review]
Are you able to leave a comment on why filtering was done by app, and why that's not needed anymore?

**Comment by ps48** [comment]
@TackAdam This is not a bug. This decision was made by the team to keep application analytics as a single entity. For the Users, App Analytics doesn't have its objects overlapping with Events and Obs. Dashboards. 

Do we have an issue where users are asking to this? or Did we discuss with the UX team for this behavior?

**Review by YANG-DB — APPROVED** [review]

**Comment by TackAdam** [comment]
> 

The existing cypress testing runs test with the impression that they will be viewable, and such fails. This led me to believe it was a bug, I can remove the cypress testing that acts under that assumption if we'd like to keep it as is.

**Comment by ps48** [comment]
The cypress tests expects that App Analytics remains separate form the other plugin components:
https://github.com/opensearch-project/dashboards-observability/blob/main/.cypress/integration/7_app_analytics.spec.js#L452-L517

**Review by ps48 — CHANGES_REQUESTED** [review]
This is by design let's not merge this.

**Pull request closed without merging**
