### PR TITLE
Logs explorer header cleanup

### PR DESCRIPTION
**Pull request by paulstn**
### Description
In log explorer, moves the granularity selector down and includes a date&time range next to it, in order to bring the UI closer in line with the rest of Opensearch. Date&time range does not change upon selection in the plot, will be dealt with in the plot selection revamp PR

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ps48** [comment]
@paulstn Can you please signoff your commits https://github.com/opensearch-project/dashboards-observability/pull/937/checks?check_run_id=15925255567

**Review by mengweieric — COMMENTED** [review]
Please address the failing tests.

**Comment by paulstn** [comment]
> @paulstn Can you please signoff your commits https://github.com/opensearch-project/dashboards-observability/pull/937/checks?check_run_id=15925255567

Signed off on all commits

**Comment by paulstn** [comment]
> Please address the failing tests.

The failing tests were due to me not signing off on all of my commits, fixed that issue

**Comment by mengweieric** [comment]
> > Please address the failing tests.
> 
> The failing tests were due to me not signing off on all of my commits, fixed that issue

Not signing off is only part of the failures, the test and build CI also fails with errors that need to be addressed. I'm seeing errors like 'FAIL public/components/event_analytics/explorer/timechart_header/__tests__/timechart_header.test.tsx (15.685 s)' which seems like changes in count distribution header caused the issue.

**Pull request closed without merging**
