### PR TITLE
BugFix Application Analytics timestamp query error

### PR DESCRIPTION
**Pull request by TackAdam**
### Description
[Describe what this change achieves]
BugFix Application Analytics timestamp query error.

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by TackAdam** [comment]
Attempt at fix with guidance from Pratik to correct the bug introduced to Application Analytics from https://github.com/opensearch-project/dashboards-observability/pull/449/ 
This change allows timestamp saves to work and application to retrieve the visual data.
This breaks Observability- Logs though when doing a refresh page resulting in the error below due to a null pointer.
 
Screenshot 2023-06-05 at 2 12 51 PM

**Comment by derek-ho** [comment]
> Attempt at fix with guidance from Pratik to correct the bug introduced to Application Analytics from #449 This change allows timestamp saves to work and application to retrieve the visual data. This breaks Observability- Logs though when doing a refresh page resulting in the error below due to a null pointer.
> 
> Screenshot 2023-06-05 at 2 12 51 PM
> Resolved by commit: [f71ad34](https://github.com/opensearch-project/dashboards-observability/pull/513/commits/f71ad34dd12f836e545f7f8d11b75899691c4527) Toaster Error appears but the refresh is working. Screenshot 2023-06-05 at 4 39 23 PM

Can you fix the toast message popping up as well?

**Review by derek-ho — APPROVED** [review]

**Review by mengweieric — APPROVED** [review]
Thanks for the fix

**Comment by mengweieric** [comment]
backporting to 2.x?

**Pull request merged**
